
version: "3.5"

services:
  # AF: TODO: Fin.
  node1:
    build:
      context: ./
      dockerfile: Dockerfile.node1
    volumes:
      # Настройки.
      - ./node1/entrypoint.sh:/entrypoint.sh
      - ./node1/share/:/share/

  # AF: TODO: Fin.
  pw1:
    build:
      context: ./
      dockerfile: Dockerfile.pw1
    ports:
      # AF: TODO: Fin. Это "UI mode".
      - 3333:3333
    volumes:
      # Настройки.
      # AF: TODO: Сначала диры, потом файлы.
      - ./pw1/share/:/share/
      - ./pw1/comfort.sh:/etc/profile.d/comfort.sh
      - ./pw1/entrypoint.sh:/entrypoint.sh
      # AF: TODO: Fin.
      #- ./pw1/try1:/mnt/try1:ro

      # Рабочий материал. Строго логический порядок!
      - ./pw1/data/pwuser-try1/:/home/pwuser/try1/
      - ./pw1/try1/lib/:/home/pwuser/try1/lib/:ro
      - ./pw1/try1/tests/:/home/pwuser/try1/tests/:ro
      - ./pw1/try1/package.json:/home/pwuser/try1/package.json:ro
      - ./pw1/try1/playwright.config.ts:/home/pwuser/try1/playwright.config.ts:ro
      - ./pw1/try1/README.md:/home/pwuser/try1/README.md:ro
      # AF: TODO: Fin. Скорее всего, не нужно.
      # - ./pw1/try1/tsconfig.json:/home/pwuser/try1/tsconfig.json:ro

      # Живучие данные.
